@startuml 
!define DC_1 #BBBBBB
!define DC_2 #535353
!define DC_4 #2B2B2B
!define DC_3 #3C3F41
!define DC_5 #438AA3
!define DC_6 #5E8A4F
!define DC_7 #589DF6
!define DC_8 #FF6464

'Red====================================================================================================================
!define MD_RED_50 #FFEBEE
!define MD_RED_100 #FFCDD2
!define MD_RED_200 #EF9A9A
!define MD_RED_300 #E57373
!define MD_RED_400 #EF5350
!define MD_RED_500 #F44336
!define MD_RED_600 #E53935
!define MD_RED_700 #D32F2F
!define MD_RED_800 #C62828
!define MD_RED_900 #B71C1C
!define MD_RED_A100 #FF8A80
!define MD_RED_A200 #FF5252
!define MD_RED_A400 #FF1744
!define MD_RED_A700 #D50000
'Pink===================================================================================================================
!define MD_PINK_50 #FCE4EC
!define MD_PINK_100 #F8BBD0
!define MD_PINK_200 #F48FB1
!define MD_PINK_300 #F06292
!define MD_PINK_400 #EC407A
!define MD_PINK_500 #E91E63
!define MD_PINK_600 #D81B60
!define MD_PINK_700 #C2185B
!define MD_PINK_800 #AD1457
!define MD_PINK_900 #880E4F
!define MD_PINK_A100 #FF80AB
!define MD_PINK_A200 #FF4081
!define MD_PINK_A400 #F50057
!define MD_PINK_A700 #C51162
'Purple=================================================================================================================
!define MD_PURPLE_50 #F3E5F5
!define MD_PURPLE_100 #E1BEE7
!define MD_PURPLE_200 #CE93D8
!define MD_PURPLE_300 #BA68C8
!define MD_PURPLE_400 #AB47BC
!define MD_PURPLE_500 #9C27B0
!define MD_PURPLE_600 #8E24AA
!define MD_PURPLE_700 #7B1FA2
!define MD_PURPLE_800 #6A1B9A
!define MD_PURPLE_900 #4A148C
!define MD_PURPLE_A100 #EA80FC
!define MD_PURPLE_A200 #E040FB
!define MD_PURPLE_A400 #D500F9
!define MD_PURPLE_A700 #AA00FF
'Deep Purple============================================================================================================
!define MD_DPURPLE_50 #EDE7F6
!define MD_DPURPLE_100 #D1C4E9
!define MD_DPURPLE_200 #B39DDB
!define MD_DPURPLE_300 #9575CD
!define MD_DPURPLE_400 #7E57C2
!define MD_DPURPLE_500 #673AB7
!define MD_DPURPLE_600 #5E35B1
!define MD_DPURPLE_700 #512DA8
!define MD_DPURPLE_800 #4527A0
!define MD_DPURPLE_900 #311B92
!define MD_DPURPLE_A100 #B388FF
!define MD_DPURPLE_A200 #7C4DFF
!define MD_DPURPLE_A400 #651FFF
!define MD_DPURPLE_A700 #6200EA
'Indigo=================================================================================================================
!define MD_INDIGO_50 #E8EAF6
!define MD_INDIGO_100 #C5CAE9
!define MD_INDIGO_200 #9FA8DA
!define MD_INDIGO_300 #7986CB
!define MD_INDIGO_400 #5C6BC0
!define MD_INDIGO_500 #3F51B5
!define MD_INDIGO_600 #3949AB
!define MD_INDIGO_700 #303F9F
!define MD_INDIGO_800 #283593
!define MD_INDIGO_900 #1A237E
!define MD_INDIGO_A100 #8C9EFF
!define MD_INDIGO_A200 #536DFE
!define MD_INDIGO_A400 #3D5AFE
!define MD_INDIGO_A700 #304FFE
'Blue===================================================================================================================
!define MD_BLUE_50 #E3F2FD
!define MD_BLUE_100 #BBDEFB
!define MD_BLUE_200 #90CAF9
!define MD_BLUE_300 #64B5F6
!define MD_BLUE_400 #42A5F5
!define MD_BLUE_500 #2196F3
!define MD_BLUE_600 #1E88E5
!define MD_BLUE_700 #1976D2
!define MD_BLUE_800 #1565C0
!define MD_BLUE_900 #0D47A1
!define MD_BLUE_A100 #82B1FF
!define MD_BLUE_A200 #448AFF
!define MD_BLUE_A400 #2979FF
!define MD_BLUE_A700 #2962FF
'Light Blue=============================================================================================================
!define MD_LBLUE_50 #E1F5FE
!define MD_LBLUE_100 #B3E5FC
!define MD_LBLUE_200 #81D4FA
!define MD_LBLUE_300 #4FC3F7
!define MD_LBLUE_400 #29B6F6
!define MD_LBLUE_500 #03A9F4
!define MD_LBLUE_600 #039BE5
!define MD_LBLUE_700 #0288D1
!define MD_LBLUE_800 #0277BD
!define MD_LBLUE_900 #01579B
!define MD_LBLUE_A100 #80D8FF
!define MD_LBLUE_A200 #40C4FF
!define MD_LBLUE_A400 #00B0FF
!define MD_LBLUE_A700 #0091EA
'Cyan===================================================================================================================
!define MD_CYAN_50 #E0F7FA
!define MD_CYAN_100 #B2EBF2
!define MD_CYAN_200 #80DEEA
!define MD_CYAN_300 #4DD0E1
!define MD_CYAN_400 #26C6DA
!define MD_CYAN_500 #00BCD4
!define MD_CYAN_600 #00ACC1
!define MD_CYAN_700 #0097A7
!define MD_CYAN_800 #00838F
!define MD_CYAN_900 #006064
!define MD_CYAN_A100 #84FFFF
!define MD_CYAN_A200 #18FFFF
!define MD_CYAN_A400 #00E5FF
!define MD_CYAN_A700 #00B8D4
'Teal===================================================================================================================
!define MD_TEAL_50 #E0F2F1
!define MD_TEAL_100 #B2DFDB
!define MD_TEAL_200 #80CBC4
!define MD_TEAL_300 #4DB6AC
!define MD_TEAL_400 #26A69A
!define MD_TEAL_500 #009688
!define MD_TEAL_600 #00897B
!define MD_TEAL_700 #00796B
!define MD_TEAL_800 #00695C
!define MD_TEAL_900 #004D40
!define MD_TEAL_A100 #A7FFEB
!define MD_TEAL_A200 #64FFDA
!define MD_TEAL_A400 #1DE9B6
!define MD_TEAL_A700 #00BFA5
'Green==================================================================================================================
!define MD_GREEN_50 #E8F5E9
!define MD_GREEN_100 #C8E6C9
!define MD_GREEN_200 #A5D6A7
!define MD_GREEN_300 #81C784
!define MD_GREEN_400 #66BB6A
!define MD_GREEN_500 #4CAF50
!define MD_GREEN_600 #43A047
!define MD_GREEN_700 #388E3C
!define MD_GREEN_800 #2E7D32
!define MD_GREEN_900 #1B5E20
!define MD_GREEN_A100 #B9F6CA
!define MD_GREEN_A200 #69F0AE
!define MD_GREEN_A400 #00E676
!define MD_GREEN_A700 #00C853
'Light Green============================================================================================================
!define MD_LGREEN_50 #F1F8E9
!define MD_LGREEN_100 #DCEDC8
!define MD_LGREEN_200 #C5E1A5
!define MD_LGREEN_300 #AED581
!define MD_LGREEN_400 #9CCC65
!define MD_LGREEN_500 #8BC34A
!define MD_LGREEN_600 #7CB342
!define MD_LGREEN_700 #689F38
!define MD_LGREEN_800 #558B2F
!define MD_LGREEN_900 #33691E
!define MD_LGREEN_A100 #CCFF90
!define MD_LGREEN_A200 #B2FF59
!define MD_LGREEN_A400 #76FF03
!define MD_LGREEN_A700 #64DD17
'Lime===================================================================================================================
!define MD_LIME_50 #F9FBE7
!define MD_LIME_100 #F0F4C3
!define MD_LIME_200 #E6EE9C
!define MD_LIME_300 #DCE775
!define MD_LIME_400 #D4E157
!define MD_LIME_500 #CDDC39
!define MD_LIME_600 #C0CA33
!define MD_LIME_700 #AFB42B
!define MD_LIME_800 #9E9D24
!define MD_LIME_900 #827717
!define MD_LIME_A100 #F4FF81
!define MD_LIME_A200 #EEFF41
!define MD_LIME_A400 #C6FF00
!define MD_LIME_A700 #AEEA00
'Yellow=================================================================================================================
!define MD_YELLOW_50 #FFFDE7
!define MD_YELLOW_100 #FFF9C4
!define MD_YELLOW_200 #FFF59D
!define MD_YELLOW_300 #FFF176
!define MD_YELLOW_400 #FFEE58
!define MD_YELLOW_500 #FFEB3B
!define MD_YELLOW_600 #FDD835
!define MD_YELLOW_700 #FBC02D
!define MD_YELLOW_800 #F9A825
!define MD_YELLOW_900 #F57F17
!define MD_YELLOW_A100 #FFFF8D
!define MD_YELLOW_A200 #FFFF00
!define MD_YELLOW_A400 #FFEA00
!define MD_YELLOW_A700 #FFD600
'Amber==================================================================================================================
!define MD_AMBER_50 #FFF8E1
!define MD_AMBER_100 #FFECB3
!define MD_AMBER_200 #FFE082
!define MD_AMBER_300 #FFD54F
!define MD_AMBER_400 #FFCA28
!define MD_AMBER_500 #FFC107
!define MD_AMBER_600 #FFB300
!define MD_AMBER_700 #FFA000
!define MD_AMBER_800 #FF8F00
!define MD_AMBER_900 #FF6F00
!define MD_AMBER_A100 #FFE57F
!define MD_AMBER_A200 #FFD740
!define MD_AMBER_A400 #FFC400
!define MD_AMBER_A700 #FFAB00
'Orange=================================================================================================================
!define MD_ORANGE_50 #FFF3E0
!define MD_ORANGE_100 #FFE0B2
!define MD_ORANGE_200 #FFCC80
!define MD_ORANGE_300 #FFB74D
!define MD_ORANGE_400 #FFA726
!define MD_ORANGE_500 #FF9800
!define MD_ORANGE_600 #FB8C00
!define MD_ORANGE_700 #F57C00
!define MD_ORANGE_800 #EF6C00
!define MD_ORANGE_900 #E65100
!define MD_ORANGE_A100 #FFD180
!define MD_ORANGE_A200 #FFAB40
!define MD_ORANGE_A400 #FF9100
!define MD_ORANGE_A700 #FF6D00
'Deep Orange============================================================================================================
!define MD_DORANGE_50 #FBE9E7
!define MD_DORANGE_100 #FFCCBC
!define MD_DORANGE_200 #FFAB91
!define MD_DORANGE_300 #FF8A65
!define MD_DORANGE_400 #FF7043
!define MD_DORANGE_500 #FF5722
!define MD_DORANGE_600 #F4511E
!define MD_DORANGE_700 #E64A19
!define MD_DORANGE_800 #D84315
!define MD_DORANGE_900 #BF360C
!define MD_DORANGE_A100 #FF9E80
!define MD_DORANGE_A200 #FF6E40
!define MD_DORANGE_A400 #FF3D00
!define MD_DORANGE_A700 #DD2C00
'Brown==================================================================================================================
!define MD_BROWN_50 #EFEBE9
!define MD_BROWN_100 #D7CCC8
!define MD_BROWN_200 #BCAAA4
!define MD_BROWN_300 #A1887F
!define MD_BROWN_400 #8D6E63
!define MD_BROWN_500 #795548
!define MD_BROWN_600 #6D4C41
!define MD_BROWN_700 #5D4037
!define MD_BROWN_800 #4E342E
!define MD_BROWN_900 #3E2723
'Grey===================================================================================================================
!define MD_GRAY_50 #FAFAFA
!define MD_GRAY_100 #F5F5F5
!define MD_GRAY_200 #EEEEEE
!define MD_GRAY_300 #E0E0E0
!define MD_GRAY_400 #BDBDBD
!define MD_GRAY_500 #9E9E9E
!define MD_GRAY_600 #757575
!define MD_GRAY_700 #616161
!define MD_GRAY_800 #424242
!define MD_GRAY_900 #212121
'Blue Grey==============================================================================================================
!define MD_BGRAY_50 #ECEFF1
!define MD_BGRAY_100 #CFD8DC
!define MD_BGRAY_200 #B0BEC5
!define MD_BGRAY_300 #90A4AE
!define MD_BGRAY_400 #78909C
!define MD_BGRAY_500 #607D8B
!define MD_BGRAY_600 #546E7A
!define MD_BGRAY_700 #455A64
!define MD_BGRAY_800 #37474F
!define MD_BGRAY_900 #263238
'Black==================================================================================================================
!define MD_BLACK #000000
'White==================================================================================================================
!define MD_WHITE #FFFFFF
' Colors
' ##################################
!define Black   #222222
!define MidnightBlue   #363D5D
!define Red     #F6363F
!define Pink    #F6216E
!define Magenta #A54FBD
!define Green   #37A77C
!define Yellow  #F97A00
!define Blue    #1E98F2
!define CYan    #25AFCA
!define AntiqueWhite   #FEF2DC
!define Grey #444444

' Normal Corlor
'---------------------
!define NOTE_BG_COLOR MD_BGRAY_300
!define NOTE_BORDER_COLOR MD_BGRAY_300

!define NOTE_Q_BG_COLOR MD_YELLOW_800
!define NOTE_Q_BORDER_COLOR MD_YELLOW_800

!define EL_BG_COLOR_900 MD_BLUE_900
!define EL_BORDER_COLOR_900 MD_BLUE_900
!define EL_BG_COLOR_800 MD_BLUE_800
!define EL_BORDER_COLOR_800 MD_BLUE_800
!define EL_BG_COLOR_600 MD_BLUE_600
!define EL_BORDER_COLOR_600 MD_BLUE_600

!define EL_BG_COLOR_400 MD_BLUE_400
!define EL_BORDER_COLOR_400 MD_BLUE_400

!define EL_BG_COLOR_300 MD_BLUE_300
!define EL_BORDER_COLOR_300 MD_BLUE_300

' C4 Colors
' ============================================
'!define ELEMENT_FONT_COLOR #FFFFFF

' Person
'!define PERSON_BG_COLOR #08427B
'!define PERSON_BORDER_COLOR #073B6F
'!define EXTERNAL_PERSON_BG_COLOR #686868
'!define EXTERNAL_PERSON_BORDER_COLOR #8A8A8A

' System
'!define SYSTEM_BG_COLOR #1168BD
'!define SYSTEM_BORDER_COLOR #3C7FC0
'!define EXTERNAL_SYSTEM_BG_COLOR #999999
'!define EXTERNAL_SYSTEM_BORDER_COLOR #8A8A8A

' Database
'!define DATABASE_BG_COLOR #1168BD
'!define DATABASE_BORDER_COLOR #3C7FC0

' Actor
'!define ACTOR_BG_COLOR #08427B
'!define ACTOR_BORDER_COLOR #073B6F
'!define INTERNAL_ACTOR_BG_COLOR #686868
'!define INTERNAL_ACTOR_BORDER_COLOR #8A8A8A

' Container
'!define CONTAINER_BG_COLOR #438DD5
'!define CONTAINER_BORDER_COLOR #3C7FC0

' Component
'!define COMPONENT_BG_COLOR #85BBF0
'!define COMPONENT_BORDER_COLOR #78A8D8
'!define COMPONENT_FONT_COLOR Black


skinparam wrapWidth 200
skinparam maxMessageSize 150
skinparam ComponentStyle uml2
skinparam Shadowing false

skinparam Default {
    FontName "'Input Mono','Microsoft YaHei Mono',Menlo, Monaco, 'Courier New', monospace"
    FontColor Black
    FontSize  14
    FontStyle plain
    Shadowing false
    TextAlignment center
    BackgroundColor MD_BLUE_50
    BorderColor MD_GRAY_800
}

skinparam Note {
    'FontStyle bold
    BackgroundColor NOTE_BG_COLOR
    BorderColor NOTE_BORDER_COLOR
    BorderThickness 1
    FontColor White
    Shadowing false
    TextAlignment left
}

skinparam Note<<quit>> {

    BackgroundColor NOTE_Q_BG_COLOR
    BorderColor NOTE_Q_BORDER_COLOR
}

skinparam Sequence {
    'ArrowThickness 1
    'ArrowColor Red
    ActorBorderThickness 1
    LifeLineBorderColor GREEN
    ParticipantBorderThickness 0
    Shadowing false


    'GroupBodyBackgroundColor
    GroupBorderThickness 1
    GroupBorderColor MD_BLUE_800
    GroupBackgroundColor MD_BLUE_100
}

skinparam Activity {

    StartColor Green
    EndColor Red
    AttributeFontColor white
    AttributeFontSize  15
    AttributeFontname  Droid Sans Mono

    BackgroundColor MD_BLUE_100
    BorderColor MD_BLUE_200
    BorderThickness 1

    ArrowThickness 1


    BarColor   MD_BLUE_900


    DiamondBackgroundColor   MD_ORANGE_100
    DiamondBorderColor    MD_ORANGE_200
    'DiamondFontColor
    'DiamondFontName
    'DiamondFontSize
    'DiamondFontStyle

    'FontColor
    'FontName
    'FontSize
    'FontStyle

}

skinparam Class {
    BackgroundColor MD_BLUE_50
    BorderColor MD_BLUE_300
    BorderThickness 1
    'FontColor
    'FontName
    'FontSize 14
    'FontStyle
    'AttributeFontColor MD_DORANGE_A700
    'AttributeFontName
    'AttributeFontSize
    'AttributeFontStyle
    'AttributeIconSize 8


    'HeaderBackgroundColor
    StereotypeFontColor DC_7
    'StereotypeFontName
    StereotypeFontSize 14
    'StereotypeFontStyle  
}



skinparam Interface {
    BackgroundColor MD_BLUE_50
    BorderColor MD_GRAY_800
    'BorderThickness
    'FontColor
    'FontName
    FontSize 14
    'FontStyle
    'AttributeFontColor MD_DORANGE_A700
    'AttributeFontName
    'AttributeFontSize
    'AttributeFontStyle
    'AttributeIconSize 8


    'HeaderBackgroundColor
    StereotypeFontColor DC_7
    'StereotypeFontName
    StereotypeFontSize 1
    'StereotypeFontStyle
}



skinparam Participant {
    BackgroundColor EL_BG_COLOR_800
    BorderColor EL_BORDER_COLOR_800
    FontColor White
    Shadowing false
}

skinparam Actor {
    BackgroundColor EL_BG_COLOR_800
    BorderColor EL_BORDER_COLOR_800
    Shadowing false
}

skinparam UseCase {
    BackgroundColor EL_BG_COLOR_300
    BorderColor EL_BG_COLOR_300
    Shadowing false
    'BackgroundColor<<Main>> YellowGreen
    'BorderColor<<Main>> YellowGreen
    'FontColor White
    ArrowThickness 1
    ArrowColor EL_BORDER_COLOR_800

    ActorBackgroundColor EL_BG_COLOR_800
    ActorBorderColor MD_BLUE_900
    ActorShadowing false
 
}


skinparam State {
    'FontColor          MD_BLUE_600   
    FontSize           17

    'AttributeFontColor MD_BLUE_300
    AttributeFontSize  14
    'AttributeFontname  Droid Sans Mono
    
    BackgroundColor    MD_BLUE_100
    BorderColor        MD_BLUE_200
    StartColor Green
    EndColor Red
}

skinparam Partition {
    BorderColor MD_GRAY_800
    BorderStyle dashed
    'BackgroundColor

    BorderThickness 1
    'FontColor
    'FontName
    'FontSize
    'FontStyle
}

skinparam rectangle {
    StereotypeFontSize 12
    shadowing false
}

skinparam database {
    StereotypeFontSize 12
    shadowing false
}

skinparam Queue {
    BackgroundColor MD_BLUE_50
    BorderColor MD_GRAY_800
}
skinparam Agent {
    BackgroundColor MD_BLUE_50
    BorderColor MD_GRAY_800
}
skinparam Artifact {
    BackgroundColor MD_BLUE_50
    BorderColor MD_GRAY_800
}

skinparam Boundary {
    BackgroundColor MD_BLUE_50
    BorderColor MD_GRAY_800
}
skinparam Card {
    BackgroundColor MD_BLUE_50
    BorderColor MD_GRAY_800
}

skinparam Cloud {
    BackgroundColor MD_BLUE_50
    BorderColor MD_GRAY_800
}

skinparam Component {
    BackgroundColor MD_BLUE_50
    BorderColor MD_GRAY_800
}
skinparam Control {
    BackgroundColor MD_BLUE_50
    BorderColor MD_GRAY_800
}
skinparam Database {
    BackgroundColor MD_BLUE_50
    BorderColor MD_GRAY_800
}

skinparam Entity {
    BackgroundColor MD_BLUE_50
    BorderColor MD_GRAY_800
}
skinparam File {
    BackgroundColor MD_BLUE_50
    BorderColor MD_GRAY_800
}
skinparam Folder {
    BackgroundColor MD_BLUE_50
    BorderColor MD_GRAY_800
   
}
skinparam Frame {
    BackgroundColor MD_BLUE_50
    BorderColor MD_GRAY_800
}
skinparam Node {
    BackgroundColor MD_BLUE_50
    BorderColor MD_GRAY_800
}


skinparam Package {
    BackgroundColor MD_BLUE_50
    BorderColor MD_GRAY_800
    'BorderStyle dashed
}
skinparam Stack {
    BackgroundColor MD_BLUE_50
    BorderColor MD_GRAY_800
}

skinparam Rectangle {
    BackgroundColor MD_BLUE_50
    BorderColor MD_GRAY_800
}

skinparam Storage {
    BackgroundColor MD_BLUE_50
    BorderColor MD_GRAY_800
}

skinparam rectangle<<usercase>> {
    Shadowing false
    StereotypeFontSize 0
    FontColor MD_GRAY_800
    BorderColor MD_GRAY_800
    BorderStyle dashed
    BackgroundColor White
}



!define TECHN_FONT_SIZE 12

!define LAYOUT_TOP_DOWN top to bottom direction
!define LAYOUT_LEFT_RIGHT left to right direction

!definelong LAYOUT_AS_SKETCH
skinparam backgroundColor #EEEBDC
skinparam handwritten true
'skinparam defaultFontName "Comic Sans MS"
center footer <font color=red>Warning:</font> Created for discussion, needs to be validated
!enddefinelong


!define RED_ARROW skinparam ArrowColor Red
!define MEGENTA_ARROW skinparam ArrowColor Magenta
!define GREEN_ARROW skinparam ArrowColor MD_GREEN_200
!define GREY_ARROW skinparam ArrowColor DC_1
!define YELLOW_ARROW skinparam ArrowColor Yellow


' help layer
!define Lay_D(e_from, e_to) e_from -[hidden]D- e_to
!define Lay_U(e_from, e_to) e_from -[hidden]U- e_to
!define Lay_R(e_from, e_to) e_from -[hidden]R- e_to
!define Lay_L(e_from, e_to) e_from -[hidden]L- e_to


!define UserCasePackage(e_alias, e_label) rectangle "==e_label" <<usercase>> as e_alias
!define UserCasePackage(e_alias, e_label, e_type) rectangle "==e_label\n<size:TECHN_FONT_SIZE>[e_type]</size>" <<usercase>> as e_alias

' Colors
' ##################################
!define ELEMENT_FONT_COLOR MD_WHITE

' Person
!define PERSON_BG_COLOR MD_BLUE_800
!define PERSON_BORDER_COLOR MD_BLUE_900
!define EXTERNAL_PERSON_BG_COLOR MD_GRAY_700
!define EXTERNAL_PERSON_BORDER_COLOR MD_GRAY_800

' System
!define SYSTEM_BG_COLOR MD_BLUE_700
!define SYSTEM_BORDER_COLOR MD_BLUE_800
!define EXTERNAL_SYSTEM_BG_COLOR MD_GRAY_600
!define EXTERNAL_SYSTEM_BORDER_COLOR MD_GRAY_700

' Database
!define DATABASE_BG_COLOR MD_BLUE_700
!define DATABASE_BORDER_COLOR MD_BLUE_800

' Actor
!define ACTOR_BG_COLOR MD_BLUE_800
!define ACTOR_BORDER_COLOR MD_BLUE_900
!define INTERNAL_ACTOR_BG_COLOR MD_GRAY_700
!define INTERNAL_ACTOR_BORDER_COLOR MD_GRAY_800

' Container
!define CONTAINER_BG_COLOR MD_BLUE_600
!define CONTAINER_BORDER_COLOR MD_BLUE_600

' Component
!define COMPONENT_BG_COLOR MD_BLUE_200
!define COMPONENT_BORDER_COLOR MD_BLUE_300
!define COMPONENT_FONT_COLOR Black

' Colors
' ##################################

' Styling
' ##################################
!define TECHN_FONT_SIZE 12


' skinparam 
' =================================
skinparam rectangle {
    StereotypeFontSize 12
    shadowing false
}

skinparam database {
    StereotypeFontSize 12
    shadowing false
}

skinparam Arrow {
    Color MD_GRAY_700
    FontColor MD_GRAY_700
    FontSize 12
}

skinparam rectangle<<boundary>> {
    Shadowing false
    StereotypeFontSize 0
    FontColor MD_GRAY_800
    BorderColor MD_GRAY_800
    BorderStyle dashed
    BackgroundColor White
}



' Boundaries
' ##################################

!define Boundary(e_alias, e_label) rectangle "==e_label" <<boundary>> as e_alias
!define Boundary(e_alias, e_label, e_type) rectangle "==e_label\n<size:TECHN_FONT_SIZE>[e_type]</size>" <<boundary>> as e_alias

' Relationship
' ##################################

!define Rel_(e_alias1, e_alias2, e_label, e_direction="") e_alias1 e_direction e_alias2 : "===e_label"
!define Rel_(e_alias1, e_alias2, e_label, e_techn, e_direction="") e_alias1 e_direction e_alias2 : "===e_label\n//<size:TECHN_FONT_SIZE>[e_techn]</size>//"

!define Rel(e_from,e_to, e_label) Rel_(e_from,e_to, e_label, "-->")
!define Rel(e_from,e_to, e_label, e_techn) Rel_(e_from,e_to, e_label, e_techn, "-->")

!define Rel_Back(e_to, e_from, e_label) Rel_(e_to, e_from, e_label, "<--")
!define Rel_Back(e_to, e_from, e_label, e_techn) Rel_(e_to, e_from, e_label, e_techn, "<--")

!define Rel_Neighbor(e_from,e_to, e_label) Rel_(e_from,e_to, e_label, "->")
!define Rel_Neighbor(e_from,e_to, e_label, e_techn) Rel_(e_from,e_to, e_label, e_techn, "->")

!define Rel_Back_Neighbor(e_to, e_from, e_label) Rel_(e_to, e_from, e_label, "<-")
!define Rel_Back_Neighbor(e_to, e_from, e_label, e_techn) Rel_(e_to, e_from, e_label, e_techn, "<-")

!define Rel_D(e_from,e_to, e_label) Rel_(e_from,e_to, e_label, "-DOWN->")
!define Rel_D(e_from,e_to, e_label, e_techn) Rel_(e_from,e_to, e_label, e_techn, "-DOWN->")
!define Rel_Down(e_from,e_to, e_label) Rel_D(e_from,e_to, e_label)
!define Rel_Down(e_from,e_to, e_label, e_techn) Rel_D(e_from,e_to, e_label, e_techn)

!define Rel_U(e_from,e_to, e_label) Rel_(e_from,e_to, e_label, "-UP->")
!define Rel_U(e_from,e_to, e_label, e_techn) Rel_(e_from,e_to, e_label, e_techn, "-UP->")
!define Rel_Up(e_from,e_to, e_label) Rel_U(e_from,e_to, e_label)
!define Rel_Up(e_from,e_to, e_label, e_techn) Rel_U(e_from,e_to, e_label, e_techn)

!define Rel_L(e_from,e_to, e_label) Rel_(e_from,e_to, e_label, "-LEFT->")
!define Rel_L(e_from,e_to, e_label, e_techn) Rel_(e_from,e_to, e_label, e_techn, "-LEFT->")
!define Rel_Left(e_from,e_to, e_label) Rel_L(e_from,e_to, e_label)
!define Rel_Left(e_from,e_to, e_label, e_techn) Rel_L(e_from,e_to, e_label, e_techn)

!define Rel_R(e_from,e_to, e_label) Rel_(e_from,e_to, e_label, "-RIGHT->")
!define Rel_R(e_from,e_to, e_label, e_techn) Rel_(e_from,e_to, e_label, e_techn, "-RIGHT->")
!define Rel_Right(e_from,e_to, e_label) Rel_R(e_from,e_to, e_label)
!define Rel_Right(e_from,e_to, e_label, e_techn) Rel_R(e_from,e_to, e_label, e_techn)



' Actors
' ##################################
skinparam actor<<person>> {
  BorderColor ACTOR_BORDER_COLOR
  BackgroundColor ACTOR_BG_COLOR
}

skinparam actor<<internal_person>> {
  BorderColor INTERNAL_ACTOR_BORDER_COLOR
  BackgroundColor INTERNAL_ACTOR_BG_COLOR
}


' Styling
' ##################################


skinparam rectangle<<person>> {
    StereotypeFontColor ELEMENT_FONT_COLOR
    FontColor ELEMENT_FONT_COLOR
    BackgroundColor PERSON_BG_COLOR
    BorderColor PERSON_BORDER_COLOR
}

skinparam rectangle<<external_person>> {
    StereotypeFontColor ELEMENT_FONT_COLOR
    FontColor ELEMENT_FONT_COLOR
    BackgroundColor EXTERNAL_PERSON_BG_COLOR
    BorderColor EXTERNAL_PERSON_BORDER_COLOR
}

skinparam rectangle<<system>> {
    StereotypeFontColor ELEMENT_FONT_COLOR
    FontColor ELEMENT_FONT_COLOR
    BackgroundColor SYSTEM_BG_COLOR
    BorderColor SYSTEM_BORDER_COLOR
}

skinparam rectangle<<external_system>> {
    StereotypeFontColor ELEMENT_FONT_COLOR
    FontColor ELEMENT_FONT_COLOR
    BackgroundColor EXTERNAL_SYSTEM_BG_COLOR
    BorderColor EXTERNAL_SYSTEM_BORDER_COLOR
}

skinparam database<<system>> {
    StereotypeFontColor ELEMENT_FONT_COLOR
    FontColor ELEMENT_FONT_COLOR
    BackgroundColor SYSTEM_BG_COLOR
    BorderColor SYSTEM_BORDER_COLOR
}

skinparam database<<external_system>> {
    StereotypeFontColor ELEMENT_FONT_COLOR
    FontColor ELEMENT_FONT_COLOR
    BackgroundColor EXTERNAL_SYSTEM_BG_COLOR
    BorderColor EXTERNAL_SYSTEM_BORDER_COLOR
}

' Layout
' ##################################
!definelong LAYOUT_WITH_LEGEND_CN
hide stereotype
legend right
|=   颜色           |= 类型 |
|<PERSON_BG_COLOR>      | 用户 |
|<EXTERNAL_PERSON_BG_COLOR>      | 外部用户 |
|<SYSTEM_BG_COLOR>   | 系统 |
|<EXTERNAL_SYSTEM_BG_COLOR>      | 外部系统 |
endlegend
!enddefinelong

!definelong LAYOUT_WITH_LEGEND
hide stereotype
legend right
|=    color          |= Type |
|<PERSON_BG_COLOR>      | person |
|<EXTERNAL_PERSON_BG_COLOR>      | external person |
|<SYSTEM_BG_COLOR>   | system |
|<EXTERNAL_SYSTEM_BG_COLOR>      | external system |
endlegend
!enddefinelong

' Elements
' ##################################

!define Actor(e_alias, e_label) actor "==e_label" <<person>> as e_alias
!define Actor(e_alias, e_label, e_descr) actor "==e_label\n\n e_descr" <<person>> as e_alias

!define Actor_Ext(e_alias, e_label) actor "==e_label" <<internal_person>> as e_alias
!define Actor_Ext(e_alias, e_label, e_descr) actor "==e_label\n\n e_descr" <<internal_person>> as e_alias


!define Person(e_alias, e_label) rectangle "==e_label" <<person>> as e_alias
!define Person(e_alias, e_label, e_descr) rectangle "==e_label\n\n e_descr" <<person>> as e_alias

!define Person_Ext(e_alias, e_label) rectangle "==e_label" <<external_person>> as e_alias
!define Person_Ext(e_alias, e_label, e_descr) rectangle "==e_label\n\n e_descr" <<external_person>> as e_alias

!define System(e_alias, e_label) rectangle "==e_label" <<system>> as e_alias
!define System(e_alias, e_label, e_descr) rectangle "==e_label\n\n e_descr" <<system>> as e_alias

!define System_Ext(e_alias, e_label) rectangle "==e_label" <<external_system>> as e_alias
!define System_Ext(e_alias, e_label, e_descr) rectangle "==e_label\n\n e_descr" <<external_system>> as e_alias

!define SystemDb(e_alias, e_label) database "==e_label" <<system>> as e_alias
!define SystemDb(e_alias, e_label, e_descr) database "==e_label\n\n e_descr" <<system>> as e_alias

!define SystemDb_Ext(e_alias, e_label) database "==e_label" <<external_system>> as e_alias
!define SystemDb_Ext(e_alias, e_label, e_descr) database "==e_label\n\n e_descr" <<external_system>> as e_alias

' Boundaries
' ##################################

!define Enterprise_Boundary(e_alias, e_label) Boundary(e_alias, e_label, "Enterprise")
!define System_Boundary(e_alias, e_label) Boundary(e_alias, e_label, "System")



' Styling
' ##################################

skinparam rectangle<<container>> {
    StereotypeFontColor ELEMENT_FONT_COLOR
    FontColor ELEMENT_FONT_COLOR
    BackgroundColor CONTAINER_BG_COLOR
    BorderColor CONTAINER_BORDER_COLOR
}

skinparam database<<container>> {
    StereotypeFontColor ELEMENT_FONT_COLOR
    FontColor ELEMENT_FONT_COLOR
    BackgroundColor CONTAINER_BG_COLOR
    BorderColor CONTAINER_BORDER_COLOR
}

' Layout
' ##################################
!definelong LAYOUT_WITH_LEGEND_CN
hide stereotype
legend right
|=    颜色          |= 类型 |
|<PERSON_BG_COLOR>      | 用户 |
|<EXTERNAL_PERSON_BG_COLOR>      | 外部用户 |
|<SYSTEM_BG_COLOR>   | 系统 |
|<EXTERNAL_SYSTEM_BG_COLOR>      | 外部系统 |
|<CONTAINER_BG_COLOR>   | 容器 |
endlegend
!enddefinelong

!definelong LAYOUT_WITH_LEGEND
hide stereotype
legend right
|=              |= Type |
|<PERSON_BG_COLOR>      | person |
|<EXTERNAL_PERSON_BG_COLOR>      | external person |
|<SYSTEM_BG_COLOR>   | system |
|<EXTERNAL_SYSTEM_BG_COLOR>      | external system |
|<CONTAINER_BG_COLOR>   | container |
endlegend
!enddefinelong

' Elements
' ##################################

!define Container(e_alias, e_label, e_techn) rectangle "==e_label\n//<size:TECHN_FONT_SIZE>[e_techn]</size>//" <<container>> as e_alias
!define Container(e_alias, e_label, e_techn, e_descr) rectangle "==e_label\n//<size:TECHN_FONT_SIZE>[e_techn]</size>//\n\n e_descr" <<container>> as e_alias

!define ContainerDb(e_alias, e_label, e_techn) database "==e_label\n//<size:TECHN_FONT_SIZE>[e_techn]</size>//" <<container>> as e_alias
!define ContainerDb(e_alias, e_label, e_techn, e_descr) database "==e_label\n//<size:TECHN_FONT_SIZE>[e_techn]</size>//\n\n e_descr" <<container>> as e_alias

' Boundaries
' ##################################

!define Container_Boundary(e_alias, e_label) Boundary(e_alias, e_label, "Container")


' Styling
' ##################################

skinparam rectangle<<component>> {
    StereotypeFontColor ELEMENT_FONT_COLOR
    FontColor COMPONENT_FONT_COLOR
    BackgroundColor COMPONENT_BG_COLOR
    BorderColor COMPONENT_BORDER_COLOR
}

skinparam database<<component>> {
    StereotypeFontColor ELEMENT_FONT_COLOR
    FontColor COMPONENT_FONT_COLOR
    BackgroundColor COMPONENT_BG_COLOR
    BorderColor COMPONENT_BORDER_COLOR
}

' Layout
' ##################################

!definelong LAYOUT_WITH_LEGEND_CN
hide stereotype
legend right
|=              |= Type |
|<PERSON_BG_COLOR>      | 用户 |
|<EXTERNAL_PERSON_BG_COLOR>      | 外部用户 |
|<SYSTEM_BG_COLOR>   | 系统 |
|<EXTERNAL_SYSTEM_BG_COLOR>      | 外部系统 |
|<CONTAINER_BG_COLOR>   | 容器 |
|<COMPONENT_BG_COLOR>   | 组件 |
endlegend
!enddefinelong


!definelong LAYOUT_WITH_LEGEND
hide stereotype
legend right
|=              |= Type |
|<PERSON_BG_COLOR>      | person |
|<EXTERNAL_PERSON_BG_COLOR>      | external person |
|<SYSTEM_BG_COLOR>   | system |
|<EXTERNAL_SYSTEM_BG_COLOR>      | external system |
|<CONTAINER_BG_COLOR>   | container |
|<COMPONENT_BG_COLOR>   | component |
endlegend
!enddefinelong

' Elements
' ##################################

!define Component(e_alias, e_label, e_techn) rectangle "==e_label\n//<size:TECHN_FONT_SIZE>[e_techn]</size>//" <<component>> as e_alias
!define Component(e_alias, e_label, e_techn, e_descr) rectangle "==e_label\n//<size:TECHN_FONT_SIZE>[e_techn]</size>//\n\n e_descr" <<component>> as e_alias

!define ComponentDb(e_alias, e_label, e_techn) database "==e_label\n//<size:TECHN_FONT_SIZE>[e_techn]</size>//" <<component>> as e_alias
!define ComponentDb(e_alias, e_label, e_techn, e_descr) database "==e_label\n//<size:TECHN_FONT_SIZE>[e_techn]</size>//\n\n e_descr" <<component>> as e_alias


!define CLASS_LINE_FONT_SIZE 12

!define Link_(e_alias1, e_alias2, e_label, e_direction="") e_alias1 e_direction e_alias2 : "e_label"
!define Link_(e_alias1, e_alias2, e_label, e_techn, e_direction="") e_alias1 e_direction e_alias2 : "e_label\n//<size:TECHN_FONT_SIZE>[e_techn]</size>//"

!define Link(e_from,e_to, e_label) Link_(e_from,e_to, e_label, "-->")
!define Link(e_from,e_to, e_label, e_techn) Link_(e_from,e_to, e_label, e_techn, "-->")

' 泛化 类继承
!define Generalize(e_from,e_to, e_label) Link_(e_from,e_to, e_label, "--|>")
!define Generalize(e_from,e_to, e_label, e_techn) Link_(e_from,e_to, e_label, e_techn, "--|>")
!define GeneralizeBack(e_from,e_to, e_label) Link_(e_from,e_to, e_label, "<|--")
!define GeneralizeBack(e_from,e_to, e_label, e_techn) Link_(e_from,e_to, e_label, e_techn, "<|--")




' 实现 
!define Realize(e_from,e_to, e_label) Link_(e_from,e_to, e_label, "..|>")
!define Realize(e_from,e_to, e_label, e_techn) Link_(e_from,e_to, e_label, e_techn, "..|>")
!define RealizeBack(e_from,e_to, e_label) Link_(e_from,e_to, e_label, "<|..")
!define RealizeBack(e_from,e_to, e_label, e_techn) Link_(e_from,e_to, e_label, e_techn, "<|..")


' 聚合 
!define Aggregation(e_from,e_to, e_label) Link_(e_from,e_to, e_label, "--o")
!define Aggregation(e_from,e_to, e_label, e_techn) Link_(e_from,e_to, e_label, e_techn, "--o")
!define AggregationBack(e_from,e_to, e_label) Link_(e_from,e_to, e_label, "o--")
!define AggregationBack(e_from,e_to, e_label, e_techn) Link_(e_from,e_to, e_label, e_techn, "o--")



' 组合
!define Composition(e_from,e_to, e_label) Link_(e_from,e_to, e_label, "--*")
!define Composition(e_from,e_to, e_label, e_techn) Link_(e_from,e_to, e_label, e_techn, "--*")
!define CompositionBack(e_from,e_to, e_label) Link_(e_from,e_to, e_label, "*--")
!define CompositionBack(e_from,e_to, e_label, e_techn) Link_(e_from,e_to, e_label, e_techn, "*--")




' 依赖
!define Dependency(e_from,e_to, e_label) Link_(e_from,e_to, e_label, "..>")
!define Dependency(e_from,e_to, e_label, e_techn) Link_(e_from,e_to, e_label, e_techn, "..>")
!define DependencyBack(e_from,e_to, e_label) Link_(e_from,e_to, e_label, "<..")
!define DependencyBack(e_from,e_to, e_label, e_techn) Link_(e_from,e_to, e_label, e_techn, "<..")


' 关联
!define Association(e_from,e_to, e_label) Link_(e_from,e_to, e_label, "--")
!define Association(e_from,e_to, e_label, e_techn) Link_(e_from,e_to, e_label, e_techn, "--")



@enduml
